#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║  zBuild installer                                                         ║
# ║  Copies pipeline tree into $ZBUILD_HOME and installs a shim on PATH.      ║
# ║  See docs/adr/ADR-023-install-isolation.md and docs/INSTALL.md.           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/helpers.sh
source "$SCRIPT_DIR/scripts/lib/helpers.sh"

info "zBuild installer"

# ─── Prereqs ────────────────────────────────────────────────────────────────
check_bin() {
    local bin="$1"
    if command -v "$bin" >/dev/null 2>&1; then
        success "found: $bin"
    else
        error "missing: $bin"
        return 1
    fi
}

prereqs_ok=true
for bin in bash git jq gh rsync; do
    check_bin "$bin" || prereqs_ok=false
done

if [[ "$prereqs_ok" != "true" ]]; then
    error "Install missing prerequisites and re-run ./install.sh"
    echo
    echo "  macOS:   brew install bash git jq gh rsync"
    echo "  Linux:   sudo apt install bash git jq gh rsync"
    exit 1
fi

if (( BASH_VERSINFO[0] < 5 )); then
    error "zBuild requires Bash 5+. You have Bash $BASH_VERSION."
    echo "  macOS: brew install bash; then add /opt/homebrew/bin/bash to /etc/shells."
    exit 1
fi
success "bash version: $BASH_VERSION"

# ─── Resolve install locations ──────────────────────────────────────────────
ZBUILD_HOME="${ZBUILD_HOME:-$HOME/.local/share/zbuild}"
TARGET_DIR="${ZBUILD_INSTALL_DIR:-$HOME/.local/bin}"
mkdir -p "$ZBUILD_HOME" "$TARGET_DIR"

# ─── Copy pipeline runtime into $ZBUILD_HOME ────────────────────────────────
# Why rsync (not cp -r):
#   --delete makes re-installs idempotent (removes stale files from a prior
#   install) and preserves permissions atomically.
# What we copy: only what runner.sh needs at runtime. tests/, docs/, legacy/,
# and .git/ are intentionally excluded.
info "copying pipeline runtime to $ZBUILD_HOME"
for d in scripts core plugins config; do
    if [[ ! -d "$SCRIPT_DIR/$d" ]]; then
        error "source directory missing: $SCRIPT_DIR/$d"
        exit 1
    fi
    rsync -a --delete "$SCRIPT_DIR/$d/" "$ZBUILD_HOME/$d/"
done

# Codex P2 on #597: tracker subcommands (manifest-sync, deferred-tracker,
# deferred-backfill, generate-issues) default to reading
# $REPO_ROOT/.github/issues/keepers-manifest.yaml. With $REPO_ROOT now
# pinned to $ZBUILD_HOME (not the source clone), those defaults break
# unless we also copy .github/issues/. Operators can still override via
# --manifest <path> to target a different repo's manifest. Follow-up:
# tracker scripts should resolve "project root" from $PWD (not $REPO_ROOT)
# so they work against arbitrary repos without bundling this snapshot.
if [[ -d "$SCRIPT_DIR/.github/issues" ]]; then
    mkdir -p "$ZBUILD_HOME/.github"
    rsync -a --delete "$SCRIPT_DIR/.github/issues/" "$ZBUILD_HOME/.github/issues/"
    success "copied scripts/ core/ plugins/ config/ .github/issues/"
else
    success "copied scripts/ core/ plugins/ config/ (no .github/issues to copy)"
fi

# ─── Capture version metadata ───────────────────────────────────────────────
# Best-effort: if the source is not a git checkout, record "unknown".
sha="unknown"; branch="unknown"
if git -C "$SCRIPT_DIR" rev-parse HEAD >/dev/null 2>&1; then
    sha="$(git -C "$SCRIPT_DIR" rev-parse HEAD)"
    branch="$(git -C "$SCRIPT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
fi
installed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$ZBUILD_HOME/version" <<VEOF
sha=$sha
branch=$branch
installed_at=$installed_at
source=$SCRIPT_DIR
VEOF
success "version: $sha ($branch) installed at $installed_at"

# ─── Install shim at TARGET_DIR/zbuild (and zb alias) ───────────────────────
# Migration: legacy installs left a symlink at TARGET_DIR/zbuild pointing into
# the source clone. We replace it with a regular-file shim so the runtime is
# decoupled from whatever branch the source clone is on.
write_shim() {
    local target="$1"
    if [[ -L "$target" ]]; then
        warn "migrating: replacing legacy symlink at $target"
        rm -f "$target"
    elif [[ -e "$target" ]]; then
        rm -f "$target"
    fi
    cat > "$target" <<SHIMEOF
#!/usr/bin/env bash
# zbuild shim — generated by install.sh ($installed_at)
# See docs/adr/ADR-023-install-isolation.md.
export ZBUILD_HOME="\${ZBUILD_HOME:-$ZBUILD_HOME}"
export ZBUILD_FROM_INSTALL=1
exec bash "\$ZBUILD_HOME/scripts/zbuild" "\$@"
SHIMEOF
    chmod +x "$target"
}
write_shim "$TARGET_DIR/zbuild"
write_shim "$TARGET_DIR/zb"
success "shim installed: $TARGET_DIR/zbuild and $TARGET_DIR/zb → $ZBUILD_HOME"

# ─── PATH check ─────────────────────────────────────────────────────────────
if [[ ":$PATH:" != *":$TARGET_DIR:"* ]]; then
    warn "$TARGET_DIR is not on your PATH"
    echo "Add this to your shell rc:"
    echo "  export PATH=\"$TARGET_DIR:\$PATH\""
fi

# ─── Smoke test ─────────────────────────────────────────────────────────────
export ZBUILD_HOME
if bash "$ZBUILD_HOME/scripts/zbuild" --version >/dev/null; then
    success "zbuild --version works"
else
    error "zbuild --version failed"
    exit 1
fi

echo
info "Installation complete. Try: zbuild --help"
info "Upgrade later with: zbuild upgrade --from <path-to-source-clone>"
