#!/usr/bin/env bash
# Tests: core/output/destinations.sh — output destination abstraction (issue #213)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=../scripts/lib/helpers.sh
source "$REPO_ROOT/scripts/lib/helpers.sh"
# shellcheck source=../scripts/lib/test-helpers.sh
source "$REPO_ROOT/scripts/lib/test-helpers.sh"

print_test_header "core/output/destinations.sh (issue #213)"

setup_test_env "core-output-destinations"

STATE_DIR="$TEST_TEMP_DIR/state"
mkdir -p "$STATE_DIR"
RUN_ID="test-run-213"
CONTENT="## zBuild Report

run ${RUN_ID}

No findings.

_0 finding(s) · generated by zBuild · run ${RUN_ID}_"

# ─── Test 1: stdout destination writes to stdout ─────────────────────────────
(
    # Re-source in subshell so toggle resets are isolated
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    unset ZBUILD_OUTPUT_STDOUT 2>/dev/null || true
    unset ZBUILD_OUTPUT_LOCAL_REPORT 2>/dev/null || true
    unset ZBUILD_OUTPUT_GH_COMMENT 2>/dev/null || true
    unset ZBUILD_OUTPUT_GH_CHECK_RUN 2>/dev/null || true
    unset ZBUILD_OUTPUT_STEP_SUMMARY 2>/dev/null || true
    unset ZBUILD_ISSUE 2>/dev/null || true
    unset GITHUB_STEP_SUMMARY 2>/dev/null || true

    source "$REPO_ROOT/core/output/destinations.sh"
    export ZBUILD_OUTPUT_LOCAL_REPORT=0
    result="$(_dest_stdout "$CONTENT" "$RUN_ID" "$STATE_DIR")"
    if echo "$result" | grep -qF "zBuild Report"; then
        echo "PASS"
    else
        echo "FAIL: stdout output missing expected content"
        exit 1
    fi
) > "$TEST_TEMP_DIR/t1_out" 2>&1
if grep -qF "PASS" "$TEST_TEMP_DIR/t1_out"; then
    assert_pass "stdout destination writes content to stdout"
else
    assert_fail "stdout destination writes content to stdout" "$(cat "$TEST_TEMP_DIR/t1_out")"
fi

# ─── Test 2: local-report creates file at correct path ───────────────────────
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    _dest_local_report "$CONTENT" "$RUN_ID" "$STATE_DIR"
)
assert_file_exists "local-report file created at state_dir/report-<run_id>.md" \
    "$STATE_DIR/report-${RUN_ID}.md"
assert_contains "local-report file contains expected content" \
    "$(cat "$STATE_DIR/report-${RUN_ID}.md")" "zBuild Report"

# ─── Test 3: gh-comment calls gh when ZBUILD_ISSUE is set ────────────────────
GH_CALL_LOG="$TEST_TEMP_DIR/gh_call_log"
cat > "$TEST_TEMP_DIR/bin/gh" <<MOCK
#!/usr/bin/env bash
printf '%s\n' "\$@" > "$GH_CALL_LOG"
exit 0
MOCK
chmod +x "$TEST_TEMP_DIR/bin/gh"

(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    export ZBUILD_ISSUE="99"
    export ZBUILD_OUTPUT_GH_COMMENT=1
    _dest_gh_comment "$CONTENT" "$RUN_ID" "$STATE_DIR"
)
assert_file_exists "gh was called (log file created)" "$GH_CALL_LOG"
assert_contains "gh called with 'issue'" "$(cat "$GH_CALL_LOG")" "issue"
assert_contains "gh called with 'comment'" "$(cat "$GH_CALL_LOG")" "comment"
assert_contains "gh called with issue number 99" "$(cat "$GH_CALL_LOG")" "99"
rm -f "$GH_CALL_LOG"

# ─── Test 4: gh-comment skipped when ZBUILD_OUTPUT_GH_COMMENT=0 ──────────────
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    export ZBUILD_ISSUE="99"
    export ZBUILD_OUTPUT_GH_COMMENT=0
    _dest_gh_comment "$CONTENT" "$RUN_ID" "$STATE_DIR"
) 2>/dev/null
if [[ -f "$GH_CALL_LOG" ]]; then
    assert_fail "gh-comment skipped when ZBUILD_OUTPUT_GH_COMMENT=0" \
        "gh was called but should have been skipped"
    rm -f "$GH_CALL_LOG"
else
    assert_pass "gh-comment skipped when ZBUILD_OUTPUT_GH_COMMENT=0"
fi

# ─── Test 5: step-summary writes to GITHUB_STEP_SUMMARY file when set ────────
SUMMARY_FILE="$TEST_TEMP_DIR/step_summary.md"
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    export GITHUB_STEP_SUMMARY="$SUMMARY_FILE"
    export ZBUILD_OUTPUT_STEP_SUMMARY=1
    _dest_step_summary "$CONTENT" "$RUN_ID" "$STATE_DIR"
)
assert_file_exists "step-summary file created" "$SUMMARY_FILE"
assert_contains "step-summary contains expected content" \
    "$(cat "$SUMMARY_FILE")" "zBuild Report"

# ─── Test 6: step-summary skipped when GITHUB_STEP_SUMMARY not set ───────────
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    unset GITHUB_STEP_SUMMARY 2>/dev/null || true
    _dest_step_summary "$CONTENT" "$RUN_ID" "$STATE_DIR"
    echo "PASS"
) > "$TEST_TEMP_DIR/t6_out" 2>&1
# Confirm the function returned without writing anywhere (rc=0, no side effects)
if grep -qF "PASS" "$TEST_TEMP_DIR/t6_out"; then
    assert_pass "step-summary skipped when GITHUB_STEP_SUMMARY not set"
else
    assert_fail "step-summary skipped when GITHUB_STEP_SUMMARY not set" \
        "$(cat "$TEST_TEMP_DIR/t6_out")"
fi

# ─── Test 7: check-run off by default ────────────────────────────────────────
GH_CHECK_LOG="$TEST_TEMP_DIR/gh_check_log"
cat > "$TEST_TEMP_DIR/bin/gh" <<MOCK
#!/usr/bin/env bash
printf '%s\n' "\$@" > "$GH_CHECK_LOG"
exit 0
MOCK
chmod +x "$TEST_TEMP_DIR/bin/gh"

(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    unset ZBUILD_OUTPUT_GH_CHECK_RUN 2>/dev/null || true
    _dest_gh_check_run "$CONTENT" "$RUN_ID" "$STATE_DIR"
) 2>/dev/null
if [[ -f "$GH_CHECK_LOG" ]]; then
    assert_fail "check-run off by default (gh should not be called)" \
        "gh was called but ZBUILD_OUTPUT_GH_CHECK_RUN defaults to 0"
    rm -f "$GH_CHECK_LOG"
else
    assert_pass "check-run off by default"
fi

# ─── Test 8: stdout disabled by ZBUILD_OUTPUT_STDOUT=0 ───────────────────────
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    export ZBUILD_OUTPUT_STDOUT=0
    result="$(_dest_stdout "$CONTENT" "$RUN_ID" "$STATE_DIR")"
    if [[ -z "$result" ]]; then
        echo "PASS"
    else
        echo "FAIL: stdout should be empty when ZBUILD_OUTPUT_STDOUT=0"
        exit 1
    fi
) > "$TEST_TEMP_DIR/t8_out" 2>&1
if grep -qF "PASS" "$TEST_TEMP_DIR/t8_out"; then
    assert_pass "stdout disabled by ZBUILD_OUTPUT_STDOUT=0"
else
    assert_fail "stdout disabled by ZBUILD_OUTPUT_STDOUT=0" "$(cat "$TEST_TEMP_DIR/t8_out")"
fi

# ─── Test 9: local-report disabled by ZBUILD_OUTPUT_LOCAL_REPORT=0 ───────────
REPORT2="$STATE_DIR/report-nodest.md"
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    export ZBUILD_OUTPUT_LOCAL_REPORT=0
    _dest_local_report "$CONTENT" "nodest" "$STATE_DIR"
)
if [[ -f "$REPORT2" ]]; then
    assert_fail "local-report disabled by ZBUILD_OUTPUT_LOCAL_REPORT=0" \
        "file was created but should not have been"
    rm -f "$REPORT2"
else
    assert_pass "local-report disabled by ZBUILD_OUTPUT_LOCAL_REPORT=0"
fi

# ─── Test 10: gh-comment skipped when ZBUILD_ISSUE not set ───────────────────
(
    unset _ZBUILD_OUTPUT_DESTINATIONS_LOADED 2>/dev/null || true
    source "$REPO_ROOT/core/output/destinations.sh"
    unset ZBUILD_ISSUE 2>/dev/null || true
    _dest_gh_comment "$CONTENT" "$RUN_ID" "$STATE_DIR"
) 2>/dev/null
if [[ -f "$GH_CALL_LOG" ]]; then
    assert_fail "gh-comment skipped when ZBUILD_ISSUE not set" \
        "gh was called but ZBUILD_ISSUE was unset"
    rm -f "$GH_CALL_LOG"
else
    assert_pass "gh-comment skipped when ZBUILD_ISSUE not set"
fi

# ─── Teardown ────────────────────────────────────────────────────────────────
cleanup_test_env
print_test_results
exit $((FAIL > 0))
