#!/usr/bin/env bash
# plugins/tool/output-github-comment — Phase 0 (issue #87)
# Aggregates findings.json artifacts, renders a markdown severity table,
# and posts to the GitHub issue (or writes a local report if no issue is set).
# Output destination abstraction (stdout, PR comment, check run) tracked in #213.

[[ -n "${_ZBUILD_OUTPUT_LOADED:-}" ]] && return 0
_ZBUILD_OUTPUT_LOADED=1

_OUTPUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_OUTPUT_ROOT="$(cd "$_OUTPUT_DIR/../../.." && pwd)"

# shellcheck source=../../../scripts/lib/helpers.sh
source "$_OUTPUT_ROOT/scripts/lib/helpers.sh"
# shellcheck source=../../../core/event-bus/event-bus.sh
source "$_OUTPUT_ROOT/core/event-bus/event-bus.sh"

# ─── helpers ─────────────────────────────────────────────────────────────────
# Sanitize a string for use in a GFM table cell: collapse newlines → space,
# escape pipe characters so the table structure doesn't break.
_md_cell() {
    printf '%s' "$1" | tr -d '\r' | tr '\n' ' ' | sed 's/|/\\|/g'
}

# ─── init ────────────────────────────────────────────────────────────────────
output_init() {
    export ZBUILD_PLUGIN="output-github-comment"
    export ZBUILD_PLUGIN_KIND="tool"
    emit_event "plugin.init.start" "plugin=output-github-comment"
    return 0
}

# ─── run ─────────────────────────────────────────────────────────────────────
# Args: $1 = stage_id (unused), $2 = state_file
# Reads: ZBUILD_ISSUE (env, optional), ZBUILD_RUN_ID (env, optional)
# Writes: $(dirname $state_file)/output-body.md
#         $(dirname $state_file)/report-<run_id>.md  (local fallback)
output_run() {
    local state_file="${2:-}"
    if [[ -z "$state_file" ]]; then
        error "output_run: state_file argument required"
        return 2
    fi

    local state_dir; state_dir="$(dirname "$state_file")"
    local artifacts_dir="$state_dir/artifacts"

    # Glob all *-findings.json files from prior analysis stages
    local findings_files=()
    while IFS= read -r f; do
        [[ -f "$f" ]] && findings_files+=("$f")
    done < <(find "$artifacts_dir" -name "*-findings.json" 2>/dev/null | sort)

    # Merge all .findings arrays — parse each file individually so one
    # malformed artifact cannot silently drop findings from all other files.
    local all_findings="[]"
    local f file_findings
    for f in "${findings_files[@]}"; do
        if file_findings="$(jq -e '.findings // []' "$f" 2>/dev/null)"; then
            all_findings="$(printf '%s\n%s' "$all_findings" "$file_findings" \
                | jq -s 'add // []' 2>/dev/null || echo "$all_findings")"
        else
            warn "output_run: skipping malformed findings file: $f"
        fi
    done

    # Sort by severity: critical=0, high=1, medium=2, low=3, else=4
    local sorted
    sorted="$(printf '%s' "$all_findings" | jq '[.[] | . + {_s: (if .severity=="critical" then 0 elif .severity=="high" then 1 elif .severity=="medium" then 2 elif .severity=="low" then 3 else 4 end)}] | sort_by(._s) | map(del(._s))' 2>/dev/null || echo '[]')"

    # Count total findings
    local count
    count="$(printf '%s' "$sorted" | jq 'length' 2>/dev/null || echo 0)"

    # Render markdown body
    local body=""

    # Header line
    local header="## zBuild Report"
    if [[ -n "${ZBUILD_ISSUE:-}" && "$ZBUILD_ISSUE" != "0" ]]; then
        header="${header}"$'\n\n'"issue #${ZBUILD_ISSUE} · run ${ZBUILD_RUN_ID:-unknown}"
    else
        header="${header}"$'\n\n'"run ${ZBUILD_RUN_ID:-unknown}"
    fi
    body="${header}"$'\n'

    # Findings table or "No findings."
    if [[ "$count" -gt 0 ]]; then
        body="${body}"$'\n'"### Findings"$'\n\n'
        body="${body}"'| Severity | Title | Category | File | Suggestion |'$'\n'
        body="${body}"'|---|---|---|---|---|'$'\n'

        while IFS= read -r finding; do
            local severity title category file_loc suggestion
            severity="$(_md_cell "$(printf '%s' "$finding" | jq -r '.severity // ""' 2>/dev/null)")"
            title="$(_md_cell "$(printf '%s' "$finding" | jq -r '.title // ""' 2>/dev/null)")"
            category="$(_md_cell "$(printf '%s' "$finding" | jq -r '.category // ""' 2>/dev/null)")"
            file_loc="$(_md_cell "$(printf '%s' "$finding" | jq -r '.file // ""' 2>/dev/null)")"
            suggestion="$(_md_cell "$(printf '%s' "$finding" | jq -r '.suggestion // ""' 2>/dev/null)")"
            body="${body}"'| '"${severity}"' | '"${title}"' | '"${category}"' | '"${file_loc}"' | '"${suggestion}"' |'$'\n'
        done < <(printf '%s' "$sorted" | jq -c '.[]' 2>/dev/null)
    else
        body="${body}"$'\n'"No findings."$'\n'
    fi

    # Footer
    body="${body}"$'\n'"_${count} finding(s) · generated by zBuild · run ${ZBUILD_RUN_ID:-unknown}_"

    # Write body atomically
    printf '%s\n' "$body" | atomic_write "$state_dir/output-body.md"

    # Destination dispatch — precedence: ZBUILD_ISSUE > ZBUILD_OUTPUT > stdout
    # Full per-destination toggle table (ZBUILD_OUTPUT_*) is deferred to #213.
    local dest
    if [[ -n "${ZBUILD_ISSUE:-}" && "$ZBUILD_ISSUE" != "0" ]]; then
        gh issue comment "$ZBUILD_ISSUE" --body-file "$state_dir/output-body.md"
        local gh_rc=$?
        if [[ $gh_rc -ne 0 ]]; then
            error "output_run: gh issue comment failed (rc=$gh_rc)"
            emit_event "plugin.run.error" "plugin=output-github-comment" \
                "reason=gh_failed" "gh_rc=$gh_rc"
            return 1
        fi
        dest="gh-issue-$ZBUILD_ISSUE"
    elif [[ -n "${ZBUILD_OUTPUT:-}" ]]; then
        mkdir -p "$(dirname "$ZBUILD_OUTPUT")" 2>/dev/null || true
        if ! cp "$state_dir/output-body.md" "$ZBUILD_OUTPUT" 2>/dev/null; then
            error "output_run: failed to write report to ZBUILD_OUTPUT=$ZBUILD_OUTPUT"
            emit_event "plugin.run.error" "plugin=output-github-comment" \
                "reason=file_write_failed" "path=$ZBUILD_OUTPUT"
            return 1
        fi
        dest="file:$ZBUILD_OUTPUT"
    else
        cat "$state_dir/output-body.md"
        dest="stdout"
    fi

    emit_event "plugin.run.complete" "plugin=output-github-comment" \
        "findings_count=$count" "dest=$dest"
    return 0
}

# ─── finalize ────────────────────────────────────────────────────────────────
output_finalize() {
    emit_event "plugin.finalize.complete" "plugin=output-github-comment"
    return 0
}
