#!/usr/bin/env bash
# Fixture helper for parity-local-vs-ci-test.sh
# NOT a test itself — runs runner.sh with mocked binaries and fixed env vars.
#
# Required env vars (set by parity-local-vs-ci-test.sh before invoking):
#   FIXTURE_STATE_DIR  — directory for state/events output
#   FIXTURE_BIN_DIR    — directory for mock binaries (prepended to PATH)
#
# Additional env vars may be set by the caller to simulate CI or local mode
# (e.g. GITHUB_ACTIONS=true, GITHUB_STEP_SUMMARY, etc.).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

# Require caller-supplied dirs
: "${FIXTURE_STATE_DIR:?FIXTURE_STATE_DIR must be set by the calling test}"
: "${FIXTURE_BIN_DIR:?FIXTURE_BIN_DIR must be set by the calling test}"

# ── Mock claude binary — returns fixed findings JSON regardless of input ──────
cat > "$FIXTURE_BIN_DIR/claude" <<'MOCK'
#!/usr/bin/env bash
cat <<'RESPONSE'
{"schema_version":1,"findings":[{"id":"parity-fixture-finding","title":"Parity fixture synthetic finding","severity":"low","stage":"security-lens","description":"Generated by parity fixture mock","recommendation":"None"}]}
RESPONSE
exit 0
MOCK
chmod +x "$FIXTURE_BIN_DIR/claude"

# ── Mock gh binary — no-op ────────────────────────────────────────────────────
cat > "$FIXTURE_BIN_DIR/gh" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
chmod +x "$FIXTURE_BIN_DIR/gh"

# ── Mock git binary — returns fixed values ────────────────────────────────────
cat > "$FIXTURE_BIN_DIR/git" <<'MOCK'
#!/usr/bin/env bash
case "${1:-}" in
    rev-parse) echo "/tmp/mock-repo" ;;
    remote)    echo "https://github.com/testuser/testrepo.git" ;;
    *)         echo "" ;;
esac
exit 0
MOCK
chmod +x "$FIXTURE_BIN_DIR/git"

# ── Wire up environment ───────────────────────────────────────────────────────
export PATH="$FIXTURE_BIN_DIR:$PATH"
export ZBUILD_STATE_DIR="$FIXTURE_STATE_DIR"
export ZBUILD_EVENTS_DIR="$FIXTURE_STATE_DIR/events"
export ZBUILD_EVENTS_JSONL="$FIXTURE_STATE_DIR/events/events.jsonl"
export ZBUILD_EVENTS_DB="/dev/null"          # exclude SQLite — JSONL only for diff
export ZBUILD_EVENT_SCHEMA="$REPO_ROOT/config/event-schema.json"
export ZBUILD_MODELS_FILE="$REPO_ROOT/config/models.json"
export ZBUILD_RUN_ID="parity-fixture-run-001"  # fixed run_id — prevents non-determinism
export NO_GITHUB=true
export ZBUILD_OUTPUT_GH_COMMENT=0
export ZBUILD_OUTPUT_GH_CHECK_RUN=0
export ZBUILD_PLATFORM_OVERRIDE=generic       # prevent platform-detection divergence

mkdir -p "$ZBUILD_EVENTS_DIR"

bash "$REPO_ROOT/core/pipeline/runner.sh" --issue 214
