#!/usr/bin/env bash
# Tests: byte-exact golden snapshots of the stage-io banner output (#499).
#
# Pairs cover paired layout (NO_COLOR=1, exact bytes, no ANSI) + colored
# (FORCE_COLOR=1 + ZBUILD_STAGE_IO_FORCE_COLOR=1, exact bytes incl ANSI):
#   - llm-plan                    (OK / no exit-code, llm kind)
#   - command-build-fail          (FAIL / exit_code=1, command kind)
# Determinism env (per ADR-015 §v5):
#   ZBUILD_TERM_WIDTH_OVERRIDE=100, ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=12345000
# Goldens are regenerated by running this file with ZBUILD_REGEN_GOLDENS=1.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GOLDEN_DIR="$REPO_ROOT/tests/golden"

# Force colors populated so the colored variant can emit ANSI.
export FORCE_COLOR=1
# shellcheck source=../../scripts/lib/helpers.sh
source "$REPO_ROOT/scripts/lib/helpers.sh"
# shellcheck source=../../scripts/lib/test-helpers.sh
source "$REPO_ROOT/scripts/lib/test-helpers.sh"

print_test_header "core/output/stage-io — banner goldens (#499)"
setup_test_env "stage-io-banner-goldens"

export ZBUILD_EVENTS_DIR="$TEST_TEMP_DIR/events"
export ZBUILD_EVENTS_JSONL="$ZBUILD_EVENTS_DIR/events.jsonl"
export ZBUILD_STATE_DIR="$TEST_TEMP_DIR/state"
export ZBUILD_RUN_ID="goldens"
mkdir -p "$ZBUILD_EVENTS_DIR" "$ZBUILD_STATE_DIR"

# shellcheck source=../../core/output/stage-io.sh
source "$REPO_ROOT/core/output/stage-io.sh"
template_stage_io_dests()      { printf 'stdout\n'; }
template_stage_io_tail_lines() { printf ''; }
template_stage_io_redact()     { printf ''; }

_reset_pending() {
    local k
    for k in "${!_STAGE_IO_PENDING[@]}";       do unset '_STAGE_IO_PENDING[$k]';       done
    for k in "${!_STAGE_IO_PENDING_INPUT[@]}"; do unset '_STAGE_IO_PENDING_INPUT[$k]'; done
    for k in "${!_STAGE_IO_PENDING_KIND[@]}";  do unset '_STAGE_IO_PENDING_KIND[$k]';  done
    for k in "${!_STAGE_IO_PENDING_DESTS[@]}"; do unset '_STAGE_IO_PENDING_DESTS[$k]'; done
    for k in "${!_STAGE_IO_START_NS[@]}";      do unset '_STAGE_IO_START_NS[$k]';      done
}

# emit_banner <mode> <stage> <kind> <input> <output> <exit_code|""> <dur_ms>
# mode: "layout" (NO_COLOR=1) or "colored" (force colors).
# Prints captured banner bytes to stdout.
emit_banner() {
    local mode="$1" stage="$2" kind="$3" input="$4" output="$5" rc="${6:-}" dur="${7:-1200}"
    local now_in=12345000 now_out=$(( 12345000 + dur ))
    local fd_file="$TEST_TEMP_DIR/banner.$$.fd"
    : > "$fd_file"
    exec 3>"$fd_file"
    local force=0 nocolor=
    [[ "$mode" == "colored" ]] && force=1
    [[ "$mode" == "layout"  ]] && nocolor=1
    _reset_pending
    rm -rf "$ZBUILD_STATE_DIR/artifacts"

    NO_COLOR="$nocolor" ZBUILD_STAGE_IO_FORCE_COLOR="$force" ZBUILD_STAGE_IO_FD=3 \
    ZBUILD_TERM_WIDTH_OVERRIDE=100 ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=$now_in \
        stage_io_begin --stage "$stage" --kind "$kind" --input "$input" >/dev/null

    local end_args=( --duration-ms "$dur" )
    [[ -n "$rc" ]] && end_args+=( --exit-code "$rc" )
    NO_COLOR="$nocolor" ZBUILD_STAGE_IO_FORCE_COLOR="$force" ZBUILD_STAGE_IO_FD=3 \
    ZBUILD_TERM_WIDTH_OVERRIDE=100 ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=$now_out \
        stage_io_end --stage "$stage" --kind "$kind" --seq "$_STAGE_IO_LAST_SEQ" \
            --output "$output" "${end_args[@]}" >/dev/null

    exec 3>&-
    cat "$fd_file"
    rm -f "$fd_file"
}

# Comparison loop: <pair_id> <mode> <stage> <kind> <input> <output> <rc> <dur>
declare -a PAIRS=(
    "llm-plan|layout |plan |llm    |PROMPT|RESPONSE| |1200"
    "llm-plan|colored|plan |llm    |PROMPT|RESPONSE| |1200"
    "command-build-fail|layout |build|command|false|boom|1|500"
    "command-build-fail|colored|build|command|false|boom|1|500"
)

for spec in "${PAIRS[@]}"; do
    IFS='|' read -r pair mode stage kind in_s out_s rc dur <<<"$spec"
    mode="${mode// /}"; stage="${stage// /}"; kind="${kind// /}"
    rc="${rc// /}"
    golden_file="$GOLDEN_DIR/banner-visual-${pair}.${mode}.golden"

    actual="$(emit_banner "$mode" "$stage" "$kind" "$in_s" "$out_s" "$rc" "$dur")"

    if [[ "${ZBUILD_REGEN_GOLDENS:-0}" == "1" ]]; then
        printf '%s' "$actual" > "$golden_file"
        assert_pass "REGEN: $(basename "$golden_file") rewritten"
        continue
    fi

    if [[ ! -f "$golden_file" ]]; then
        assert_fail "golden file exists: $(basename "$golden_file")" "missing — re-run with ZBUILD_REGEN_GOLDENS=1"
        continue
    fi
    expected="$(cat "$golden_file")"
    if [[ "$expected" == "$actual" ]]; then
        assert_pass "byte-exact: $(basename "$golden_file")"
    else
        # Diff is noisy with ANSI; show a brief delta via cmp byte offset.
        local_diff="$(diff <(printf '%s' "$expected") <(printf '%s' "$actual") | head -20 || true)"
        assert_fail "byte-exact: $(basename "$golden_file")" "diff (first 20 lines):
$local_diff"
    fi
done

cleanup_test_env
print_test_results
exit "$FAIL"
