#!/usr/bin/env bash
# Tests: byte-exact golden snapshots of runner stage-boundary banners (#508).
#
# Pairs (layout = NO_COLOR=1, colored = FORCE_COLOR=1):
#   - divider-plan-w100   _render_stage_divider plan @ w=100
#   - running-plan-w100   "▸ Running stage: plan  (started ...)" line
#   - complete-plan-w100  "✓ Stage plan complete  (finished ... · 0.4s)" line
#   - failed-build-w100   "✗ Stage build failed (rc=1, finished ... · 0.5s)"
#
# Determinism env (ADR-015 §v5 amendment, #508):
#   ZBUILD_TERM_WIDTH_OVERRIDE=100  ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=12345000
# Goldens are regenerated by running this file with ZBUILD_REGEN_GOLDENS=1.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GOLDEN_DIR="$REPO_ROOT/tests/golden/runner-stage-banners"

# shellcheck source=../../scripts/lib/test-helpers.sh
source "$REPO_ROOT/scripts/lib/test-helpers.sh"

print_test_header "core/pipeline/runner — stage-banner goldens (#508)"
setup_test_env "runner-stage-banner-goldens"

mkdir -p "$GOLDEN_DIR"

# emit_runner_banner <mode> <variant>
# Emits the named banner under either the layout (NO_COLOR=1) or colored
# (FORCE_COLOR=1) env. Runs in a clean subshell so helpers.sh re-initializes
# the color palette under the requested mode.
emit_runner_banner() {
    local mode="$1" variant="$2"
    local env_pre=""
    if [[ "$mode" == "layout" ]]; then
        env_pre="unset FORCE_COLOR; export NO_COLOR=1"
    else
        env_pre="unset NO_COLOR; export FORCE_COLOR=1"
    fi

    bash -c "
        $env_pre
        export ZBUILD_TERM_WIDTH_OVERRIDE=100
        export ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=12345000
        export ZBUILD_STATE_DIR='$TEST_TEMP_DIR/state'
        export ZBUILD_EVENTS_DIR='$TEST_TEMP_DIR/events'
        export ZBUILD_EVENTS_JSONL='$TEST_TEMP_DIR/events/events.jsonl'
        mkdir -p \"\$ZBUILD_STATE_DIR\" \"\$ZBUILD_EVENTS_DIR\"
        source '$REPO_ROOT/core/pipeline/runner.sh'

        case '$variant' in
            divider-plan-w100)
                _render_stage_divider plan
                ;;
            running-plan-w100)
                _sc_color=\"\$(_stage_color plan)\"
                _sc_ts=\"\$(_runner_now_short)\"
                echo -e \"\${CYAN}\${BOLD}▸\${RESET} Running stage: \${_sc_color}\${BOLD}plan\${RESET}  \${DIM}(started \${_sc_ts})\${RESET}\"
                ;;
            complete-plan-w100)
                _RUNNER_STAGE_START_MS[plan]=12345000
                export ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=12345400
                _cc=\"\$(_stage_color plan)\"
                _cc_ts=\"\$(_runner_now_short)\"
                _cc_dur=\"\$(_runner_duration_token plan)\"
                echo -e \"\${GREEN}\${BOLD}✓\${RESET} Stage \${_cc}\${BOLD}plan\${RESET} complete  \${DIM}(finished \${_cc_ts} · \${_cc_dur})\${RESET}\"
                ;;
            failed-build-w100)
                _RUNNER_STAGE_START_MS[build]=12345000
                export ZBUILD_STAGE_IO_NOW_MS_OVERRIDE=12345500
                _f2_ts=\"\$(_runner_now_short)\"
                _f2_dur=\"\$(_runner_duration_token build)\"
                error \"Stage build failed (rc=1, finished \${_f2_ts} · \${_f2_dur})\"
                ;;
        esac
    " 2>&1
}

# Pair table: variant|modes
declare -a VARIANTS=(
    "divider-plan-w100"
    "running-plan-w100"
    "complete-plan-w100"
    "failed-build-w100"
)
declare -a MODES=("layout" "colored")

for variant in "${VARIANTS[@]}"; do
    for mode in "${MODES[@]}"; do
        golden_file="$GOLDEN_DIR/${variant}.${mode}.txt"
        actual="$(emit_runner_banner "$mode" "$variant")"

        if [[ "${ZBUILD_REGEN_GOLDENS:-0}" == "1" ]]; then
            printf '%s' "$actual" > "$golden_file"
            assert_pass "REGEN: $(basename "$golden_file") rewritten"
            continue
        fi

        if [[ ! -f "$golden_file" ]]; then
            assert_fail "$(basename "$golden_file") missing" \
                "run with ZBUILD_REGEN_GOLDENS=1 to create"
            continue
        fi

        expected="$(cat "$golden_file")"
        if [[ "$actual" == "$expected" ]]; then
            assert_pass "byte-exact match: $(basename "$golden_file")"
        else
            assert_fail "byte-exact match: $(basename "$golden_file")" \
                "diff (see ZBUILD_REGEN_GOLDENS=1 to regen)"
            diff <(printf '%s' "$expected") <(printf '%s' "$actual") || true
        fi
    done
done

cleanup_test_env
print_test_results
exit "$FAIL"
