#!/usr/bin/env bash
# Unit: _render_cycle_entry's optional <description> 4th arg renders as a
# DIM line between the "Entering cycle:" headline and the (max_iterations=…)
# trailer (#831). When absent, the banner is byte-identical to the pre-#831
# shape — golden snapshot at tests/golden/cycle-banners/entry-build-test.*
# is unchanged.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=../../scripts/lib/test-helpers.sh
source "$REPO_ROOT/scripts/lib/test-helpers.sh"
print_test_header "unit: _render_cycle_entry description arg (#831)"
setup_test_env "runner-cycle-banner-description-831"

# Stable terminal width for deterministic divider math.
export ZBUILD_TERM_WIDTH_OVERRIDE=100

# shellcheck source=../../core/pipeline/runner.sh
source "$REPO_ROOT/core/pipeline/runner.sh"

# ─── T1: description passed → DIM line emitted between headline and trailer ─
OUT1="$TEST_TEMP_DIR/with-desc.stderr"
_render_cycle_entry build-test 5 'build,test' 'Iterate until verdict pass' 2> "$OUT1"
if grep -q 'Entering cycle: build-test' "$OUT1"; then
    assert_pass "T1: headline 'Entering cycle: build-test' present"
else
    assert_fail "T1: headline missing" "captured: $(head -5 "$OUT1")"
fi
if grep -qF 'Iterate until verdict pass' "$OUT1"; then
    assert_pass "T1: description text rendered in banner"
else
    assert_fail "T1: description text missing" "captured: $(head -5 "$OUT1")"
fi
# Description line MUST come before the trailer (operator scan order).
desc_line=$(grep -n 'Iterate until verdict pass' "$OUT1" | head -1 | cut -d: -f1)
trail_line=$(grep -n 'max_iterations=' "$OUT1" | head -1 | cut -d: -f1)
if [[ -n "$desc_line" ]] && [[ -n "$trail_line" ]] && [[ "$desc_line" -lt "$trail_line" ]]; then
    assert_pass "T1: description line precedes (max_iterations=…) trailer"
else
    assert_fail "T1: description line position wrong" \
        "desc=$desc_line trailer=$trail_line"
fi

# ─── T2: empty description → no extra line; banner shape unchanged ────────
OUT2="$TEST_TEMP_DIR/empty-desc.stderr"
_render_cycle_entry build-test 5 'build,test' '' 2> "$OUT2"
# Direct file-based line count (wc -l counts \n; banner has 5 \n bytes).
n=$(wc -l < "$OUT2" | tr -d ' ')
if [[ "$n" -eq 5 ]]; then
    assert_pass "T2: empty description → 5 newlines (no extra DIM line added)"
else
    assert_fail "T2: empty description has unexpected line count" \
        "got $n; expected 5"
fi

# ─── T3: omitted description arg (back-compat with 3-arg callers) ────────
OUT3="$TEST_TEMP_DIR/omitted-arg.stderr"
_render_cycle_entry build-test 5 'build,test' 2> "$OUT3"
n=$(wc -l < "$OUT3" | tr -d ' ')
if [[ "$n" -eq 5 ]]; then
    assert_pass "T3: 3-arg call → 5 newlines (back-compat with 4-arg-empty)"
else
    assert_fail "T3: 3-arg call line count differs from 4-arg-empty" \
        "got $n; expected 5"
fi
# Also assert OUT3 byte-equal to OUT2 (3-arg ≡ 4-arg-with-empty).
if cmp -s "$OUT2" "$OUT3"; then
    assert_pass "T3: 3-arg call byte-identical to 4-arg-with-empty"
else
    assert_fail "T3: 3-arg call differs from 4-arg-with-empty" \
        "diff: $(diff "$OUT2" "$OUT3" | head -5)"
fi

# ─── T3b: with-description has 6 newlines (one more for DIM desc line) ────
OUT3B="$TEST_TEMP_DIR/with-desc.stderr"
_render_cycle_entry build-test 5 'build,test' 'Has a description' 2> "$OUT3B"
n=$(wc -l < "$OUT3B" | tr -d ' ')
if [[ "$n" -eq 6 ]]; then
    assert_pass "T3b: with-description → 6 newlines (one extra DIM line)"
else
    assert_fail "T3b: with-description line count wrong" \
        "got $n; expected 6"
fi

# ─── T4: golden snapshot unchanged ────────────────────────────────────────
# When description is omitted, the rendered banner must match the existing
# golden at tests/golden/cycle-banners/entry-build-test.layout.txt byte for
# byte (assuming color env is the same as the golden test sets up).
GOLDEN_LAYOUT="$REPO_ROOT/tests/golden/cycle-banners/entry-build-test.layout.txt"
if [[ -s "$GOLDEN_LAYOUT" ]]; then
    # Content-equivalence: golden contains the pre-#831 headline. OUT3 (3-arg
    # call → no description path) must contain the same headline. Exact-byte
    # parity isn't asserted because the golden is generated by a different
    # harness with different ANSI/width settings.
    if grep -q 'Entering cycle: build-test' "$GOLDEN_LAYOUT" && \
       grep -q 'Entering cycle: build-test' "$OUT3"; then
        assert_pass "T4: golden + 3-arg banner both contain pre-#831 headline"
    else
        assert_fail "T4: golden vs 3-arg headline divergence" \
            "golden head: $(head -5 "$GOLDEN_LAYOUT" | tr -d '\033')"
    fi
else
    assert_fail "T4: golden file missing at $GOLDEN_LAYOUT"
fi

cleanup_test_env
print_test_results
exit $((FAIL > 0))
